import React, { useState } from 'react';

const DISCLAIMER = `NestureAI is an educational technology platform. All information generated by NestureAI — including child profiles, insights, home plans and specialist recommendations — is for educational and informational purposes only. NestureAI does not provide medical advice, medical diagnosis, therapeutic treatment or professional assessment of any kind. The insights generated by NestureAI are based on documents uploaded by the user and do not constitute a medical, psychological, neurological or educational evaluation. NestureAI is not a substitute for qualified professional advice from an occupational therapist, speech and language pathologist, physician, psychologist or any other licensed professional. Always consult a qualified professional before making decisions about your child's health, education or support. Functional wellness insights are educational inferences based on uploaded documents only — they are not medical diagnoses and should not be acted upon without consulting a qualified healthcare professional.`;

/**
 * BetaFooter — PRD v4.0 compliance.
 * Must appear on every page.
 * Supports two variants: 'light' (for white-background pages) and 'dark' (for dark-background pages).
 * Includes a collapsible disclaimer for compact layouts.
 */
export default function BetaFooter({ variant = 'light' }) {
  const [expanded, setExpanded] = useState(false);
  const isDark = variant === 'dark';

  return (
    <div style={{
      ...s.footer,
      borderTop: isDark ? '1px solid rgba(255,255,255,0.06)' : '1px solid #E5E7EB',
    }}>
      <div style={s.topRow}>
        <div style={{
          ...s.badge,
          background: isDark ? 'rgba(245,158,11,0.1)' : '#FEF3C7',
          color: isDark ? '#FCD34D' : '#92400E',
          border: isDark ? '1px solid rgba(245,158,11,0.2)' : '1px solid #FDE68A',
        }}>
          <span style={{
            display: 'inline-block', width: 5, height: 5, borderRadius: '50%',
            background: isDark ? '#FCD34D' : '#D97706',
          }} />
          NestureAI Beta v4.0
        </div>

        <button
          onClick={() => setExpanded(!expanded)}
          style={{
            ...s.toggleBtn,
            color: isDark ? 'rgba(200,232,237,0.4)' : '#9CA3AF',
          }}
        >
          {expanded ? 'Hide disclaimer ▲' : 'Show disclaimer ▼'}
        </button>
      </div>

      {/* Always-visible short notice */}
      <p style={{
        ...s.shortNotice,
        color: isDark ? 'rgba(200,232,237,0.35)' : '#9CA3AF',
      }}>
        For educational and informational purposes only. Not a substitute for professional advice.
      </p>

      {/* Expandable full disclaimer */}
      <div style={{
        ...s.disclaimerWrap,
        maxHeight: expanded ? 300 : 0,
        opacity: expanded ? 1 : 0,
        marginTop: expanded ? 8 : 0,
      }}>
        <p style={{
          ...s.disclaimer,
          color: isDark ? 'rgba(200,232,237,0.3)' : '#9CA3AF',
        }}>
          {DISCLAIMER}
        </p>
      </div>
    </div>
  );
}

const s = {
  footer: {
    marginTop: 32,
    paddingTop: 16,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 6,
  },
  topRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    fontSize: '0.65rem',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    padding: '4px 12px',
    borderRadius: 20,
  },
  toggleBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.62rem',
    fontWeight: 600,
    fontFamily: "'Inter', sans-serif",
    letterSpacing: '0.04em',
    transition: 'color 0.2s',
  },
  shortNotice: {
    fontSize: '0.65rem',
    textAlign: 'center',
    lineHeight: 1.5,
    margin: 0,
    fontStyle: 'italic',
  },
  disclaimerWrap: {
    overflow: 'hidden',
    transition: 'all 0.3s ease',
  },
  disclaimer: {
    fontSize: '0.62rem',
    textAlign: 'center',
    lineHeight: 1.7,
    maxWidth: 600,
    margin: 0,
    padding: '8px 12px',
    borderRadius: 8,
  },
};
