import React, { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import toast from 'react-hot-toast';
import { Eye, EyeOff } from 'lucide-react';
import { getRouteForRole } from '../services/authService';
import { validateEmail, validatePassword, validateName, sanitizeInput } from '../utils/security';
import { supabase } from '../services/supabaseClient';
import { useAuthStore } from '../store';
import BetaFooter from '../components/shared/BetaFooter';

const CONSENT_POINTS = [
  {
    id: 'educational',
    title: 'Educational purpose',
    text: 'I understand that insights, profiles and recommendations generated by NestureAI are for informational purposes only and do not constitute professional medical, therapeutic or educational advice.',
  },
  {
    id: 'document_processing',
    title: 'Document processing',
    text: 'I agree that NestureAI will process my uploaded documents for the sole purpose of generating the learning and movement profile. Documents are processed and then deleted. Only the structured profile output is retained.',
  },
  {
    id: 'data_privacy',
    title: 'Data privacy',
    text: 'I understand that NestureAI stores profile data securely and does not share it with third parties. NestureAI complies with COPPA for learners under 13 and FERPA where educational records are involved.',
  },
  {
    id: 'practitioner_sharing',
    title: 'Specialist sharing',
    text: 'I consent to sharing the sections of the profile with specialists I choose to connect with: strengths, challenges, communication profile, sensory profile, functional wellness insights and primitive motor reflex profile. I can withdraw this consent at any time.',
  },
  {
    id: 'no_guarantee',
    title: 'No guarantee of outcomes',
    text: 'I understand that NestureAI does not guarantee any specific educational, developmental or motor outcome.',
  },
  {
    id: 'beta_participation',
    title: 'Beta participation',
    text: 'I understand that I am using a beta version of NestureAI which may contain errors or limitations. I agree to provide feedback to help improve the platform.',
  },
  {
    id: 'functional_wellness',
    title: 'Functional wellness content',
    text: 'I acknowledge that any functional wellness insights generated by NestureAI are educational inferences based on my uploaded documents. They are not medical diagnoses and I agree to consult a qualified professional before acting on them.',
  },
];

export default function SignUpPage() {
  const navigate = useNavigate();

  const [step,       setStep]       = useState(1);
  const [firstName,  setFirstName]  = useState('');
  const [lastName,   setLastName]   = useState('');
  const [email,      setEmail]      = useState('');
  const [password,   setPassword]   = useState('');
  const [confirm,    setConfirm]    = useState('');
  const [agreed,     setAgreed]     = useState(false);
  const [loading,    setLoading]    = useState(false);
  const [error,      setError]      = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);

  const [firstNameError, setFirstNameError] = useState('');
  const [lastNameError, setLastNameError] = useState('');
  const [emailError, setEmailError] = useState('');
  const [passwordError, setPasswordError] = useState('');
  const [confirmError, setConfirmError] = useState('');

  const handleFirstNameChange = (val) => {
    setFirstName(val);
    if (!val) {
      setFirstNameError('');
    } else {
      try {
        validateName(val, 'First name');
        setFirstNameError('');
      } catch (err) {
        setFirstNameError(err.message);
      }
    }
  };

  const handleFirstNameBlur = () => {
    const trimmed = firstName.trim();
    setFirstName(trimmed);
    if (!trimmed) {
      setFirstNameError('First name is required.');
    } else {
      try {
        validateName(trimmed, 'First name');
        setFirstNameError('');
      } catch (err) {
        setFirstNameError(err.message);
      }
    }
  };

  const handleLastNameChange = (val) => {
    setLastName(val);
    if (!val) {
      setLastNameError('');
    } else {
      try {
        validateName(val, 'Last name');
        setLastNameError('');
      } catch (err) {
        setLastNameError(err.message);
      }
    }
  };

  const handleLastNameBlur = () => {
    const trimmed = lastName.trim();
    setLastName(trimmed);
    if (trimmed !== '') {
      try {
        validateName(trimmed, 'Last name');
        setLastNameError('');
      } catch (err) {
        setLastNameError(err.message);
      }
    } else {
      setLastNameError('');
    }
  };

  const handleEmailChange = (val) => {
    setEmail(val);
    if (!val) {
      setEmailError('');
    } else {
      try {
        validateEmail(val);
        setEmailError('');
      } catch (err) {
        setEmailError(err.message);
      }
    }
  };

  const handleEmailBlur = () => {
    const trimmed = email.trim();
    setEmail(trimmed);
    if (!trimmed) {
      setEmailError('Email address is required.');
    } else {
      try {
        validateEmail(trimmed);
        setEmailError('');
      } catch (err) {
        setEmailError(err.message);
      }
    }
  };

  const handlePasswordChange = (val) => {
    setPassword(val);
    if (!val) {
      setPasswordError('');
    } else {
      try {
        validatePassword(val);
        setPasswordError('');
      } catch (err) {
        setPasswordError(err.message);
      }
    }
  };

  const handlePasswordBlur = () => {
    const trimmed = password.trim();
    setPassword(trimmed);
    if (!trimmed) {
      setPasswordError('Password is required.');
    } else {
      try {
        validatePassword(trimmed);
        setPasswordError('');
      } catch (err) {
        setPasswordError(err.message);
      }
    }
  };

  const handleConfirmChange = (val) => {
    setConfirm(val);
    if (!val) {
      setConfirmError('');
    } else {
      if (password && val !== password) {
        setConfirmError('Passwords do not match.');
      } else {
        setConfirmError('');
      }
    }
  };

  const handleConfirmBlur = () => {
    const trimmed = confirm.trim();
    setConfirm(trimmed);
    if (trimmed !== password) {
      setConfirmError('Passwords do not match.');
    } else {
      setConfirmError('');
    }
  };

  const handleStep1 = (e) => {
    e.preventDefault();
    setError('');

    const cleanFirstName = firstName.trim();
    const cleanLastName = lastName.trim();
    const cleanEmail = email.trim();
    const cleanPassword = password.trim();
    const cleanConfirm = confirm.trim();

    setFirstName(cleanFirstName);
    setLastName(cleanLastName);
    setEmail(cleanEmail);
    setPassword(cleanPassword);
    setConfirm(cleanConfirm);

    // Strict input validations
    try {
      validateEmail(cleanEmail);
      validatePassword(cleanPassword);
      validateName(cleanFirstName, 'First name');
      if (cleanLastName !== '') {
        validateName(cleanLastName, 'Last name');
      }
    } catch (valErr) {
      setError(valErr.message);
      return;
    }

    if (cleanPassword !== cleanConfirm) { 
      setError('Passwords do not match.'); 
      return; 
    }

    setStep(2);
  };

  const handleSignUp = async () => {
    if (!agreed) { 
      toast.error('Please agree to all terms to continue.'); 
      return; 
    }
    setLoading(true);
    setError('');
    
    try {
      const { signup } = useAuthStore.getState();
      await signup({
        email: email.trim(), 
        password: password.trim(), 
        firstName: firstName.trim(), 
        lastName: lastName.trim(), 
        role: 'parent', 
        consentAccepted: true,
      });

      // Verification is mandatory. Supabase will not log user in automatically.
      const { data: { session } } = await supabase.auth.getSession();

      if (session) {
        // Fallback in case email verification is disabled in development env
        const { setAuth } = useAuthStore.getState();
        const { getUserProfile } = await import('../services/supabaseClient');
        let profile = null;
        try {
          profile = await getUserProfile(session.user.id);
        } catch (profileErr) {
          console.warn('[SignUpPage] Profile fetch failed, attempting client-side fallback:', profileErr.message);
          const { ensureUserProfileFallback } = await import('../services/authService');
          profile = await ensureUserProfileFallback(session.user, 'parent').catch((err) => {
            console.error('[SignUpPage] Fallback profile creation failed:', err.message);
            return null;
          });
        }

        if (!profile) {
          throw new Error(`No profile found in public.users for auth ID: ${session.user.id}. Run the demo seed SQL.`);
        }

        setAuth({ user: session.user, profile });
        toast.success(`Welcome to NestureAI Beta, ${firstName}! 🎉`);
        navigate(getRouteForRole(profile.role));
      } else {
        toast.success('Account created successfully! Please verify your email before continuing.');
        navigate(`/verify-email?email=${encodeURIComponent(email.trim())}`);
      }
    } catch (err) {
      if (err.message.includes('User already registered')) {
        setError('This email address is already registered. Please sign in instead.');
      } else {
        setError(err.message);
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={s.root}>
      <style>{`
        @media (max-width: 600px) {
          #signup-card { padding: 24px 20px !important; border-radius: 16px !important; }
          #signup-row { grid-template-columns: 1fr !important; }
          #signup-title { font-size: 1.25rem !important; }
        }
      `}</style>
      <motion.div id="signup-card" style={s.card} initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>

        {/* Header */}
        <div style={s.header}>
          <div style={s.logoRow}>
            <img src="/logo.png" alt="NestureAI Logo" style={{ width: 36, height: 36, objectFit: 'contain' }} />
            <div style={{ ...s.logoName, whiteSpace: 'nowrap' }}>
              <span style={{ color: '#0D5E6B' }}>Nesture</span>
              <span style={{ color: '#F59E0B' }}>AI</span>
            </div>
          </div>
          <div style={s.progressBar}>
            <div style={{ ...s.progressFill, width: step === 1 ? '50%' : '100%' }} />
          </div>
          <div style={s.stepLabel}>Step {step} of 2</div>
        </div>

        <AnimatePresence mode="wait">
          {step === 1 ? (
            <motion.form key="step1" onSubmit={handleStep1} style={s.form}
              initial={{ opacity: 0, x: 30 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -30 }}>

              <h2 id="signup-title" style={s.title}>Join NestureAI Beta</h2>
              <p style={s.sub}>You're joining as a beta participant</p>

              {/* Role Selector removed: Only parents can create accounts */}

              <div id="signup-row" style={s.row}>
                <div style={s.field}>
                  <label style={s.label}>First name</label>
                  <input 
                    style={s.input} 
                    value={firstName} 
                    onChange={(e) => handleFirstNameChange(e.target.value)} 
                    onBlur={handleFirstNameBlur}
                    required 
                    placeholder="Jennifer" 
                    autoComplete="given-name"
                  />
                  {firstNameError && <div style={s.inlineError}>{firstNameError}</div>}
                </div>
                <div style={s.field}>
                  <label style={s.label}>Last name</label>
                  <input 
                    style={s.input} 
                    value={lastName} 
                    onChange={(e) => handleLastNameChange(e.target.value)} 
                    onBlur={handleLastNameBlur}
                    placeholder="Chen" 
                    autoComplete="family-name"
                  />
                  {lastNameError && <div style={s.inlineError}>{lastNameError}</div>}
                </div>
              </div>
              <div style={s.field}>
                <label style={s.label}>Email</label>
                <input 
                  style={s.input} 
                  type="email" 
                  value={email} 
                  onChange={(e) => handleEmailChange(e.target.value)} 
                  onBlur={handleEmailBlur}
                  required 
                  placeholder="you@example.com" 
                  autoComplete="email"
                />
                {emailError && <div style={s.inlineError}>{emailError}</div>}
              </div>
              <div style={s.field}>
                <label style={s.label}>Password</label>
                <div style={{ position: 'relative', display: 'flex', alignItems: 'center' }}>
                  <input 
                    style={{ ...s.input, width: '100%', paddingRight: 40 }} 
                    type={showPassword ? 'text' : 'password'} 
                    value={password} 
                    onChange={(e) => handlePasswordChange(e.target.value)} 
                    onBlur={handlePasswordBlur}
                    required 
                    placeholder="Min. 8 characters" 
                    autoComplete="new-password"
                  />
                  <button type="button" onClick={() => setShowPassword(!showPassword)} style={s.eyeBtn}>
                    {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
                  </button>
                </div>
                {passwordError && <div style={{ ...s.inlineError, marginTop: 4 }}>{passwordError}</div>}
              </div>
              <div style={s.field}>
                <label style={s.label}>Confirm password</label>
                <div style={{ position: 'relative', display: 'flex', alignItems: 'center' }}>
                  <input 
                    style={{ ...s.input, width: '100%', paddingRight: 40 }} 
                    type={showConfirm ? 'text' : 'password'} 
                    value={confirm} 
                    onChange={(e) => handleConfirmChange(e.target.value)} 
                    onBlur={handleConfirmBlur}
                    required 
                    placeholder="••••••••" 
                    autoComplete="new-password"
                  />
                  <button type="button" onClick={() => setShowConfirm(!showConfirm)} style={s.eyeBtn}>
                    {showConfirm ? <EyeOff size={18} /> : <Eye size={18} />}
                  </button>
                </div>
                {confirmError && <div style={{ ...s.inlineError, marginTop: 4 }}>{confirmError}</div>}
              </div>
              {error && <p style={s.errorMsg}>{error}</p>}

              <button type="submit" disabled={!!firstNameError || !!lastNameError || !!emailError || !!passwordError || !!confirmError} style={{ ...s.primaryBtn, opacity: (!!firstNameError || !!lastNameError || !!emailError || !!passwordError || !!confirmError) ? 0.6 : 1 }}>Continue →</button>
              <p style={s.backLink}>Already have an account? <Link to="/login" style={s.link}>Sign in</Link></p>
            </motion.form>
          ) : (
            <motion.div key="step2" style={s.form}
              initial={{ opacity: 0, x: 30 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -30 }}>

              <h2 style={s.title}>Before we get started</h2>
              <p style={s.sub}>Please read and agree to the following before creating your account.</p>

              {/* Specialist Notice Removed */}

              <div style={s.consentList}>
                {CONSENT_POINTS.map((pt) => (
                  <div key={pt.id} style={s.consentItem}>
                    <div style={s.consentTitle}>{pt.title}</div>
                    <div style={s.consentText}>{pt.text}</div>
                  </div>
                ))}
              </div>

              <label style={s.checkboxRow}>
                <input type="checkbox" checked={agreed} onChange={(e) => setAgreed(e.target.checked)} style={{ accentColor: '#0D5E6B', width: 16, height: 16 }} />
                <span style={s.checkboxLabel}>I have read and agree to all of the above</span>
              </label>

              {error && <p style={s.errorMsg}>{error}</p>}

              <button onClick={handleSignUp} disabled={!agreed || loading} style={{ ...s.primaryBtn, opacity: (!agreed || loading) ? 0.5 : 1 }}>
                {loading ? 'Creating account…' : 'Create Account'}
              </button>
              <button onClick={() => setStep(1)} style={s.secondaryBtn}>← Back</button>
            </motion.div>
          )}
        </AnimatePresence>

        <BetaFooter />
      </motion.div>
    </div>
  );
}

const s = {
  root:         { minHeight: '100vh', background: '#F0F4F8', display: 'flex', alignItems: 'flex-start', justifyContent: 'center', padding: '40px 16px' },
  card:         { background: '#fff', borderRadius: 20, boxShadow: '0 12px 48px rgba(0,0,0,0.1)', padding: '36px 40px', width: '100%', maxWidth: 540 },
  header:       { marginBottom: 28 },
  logoRow:      { display: 'flex', alignItems: 'center', gap: 10, marginBottom: 20 },
  logoName:     { fontFamily: 'Inter, sans-serif', fontWeight: 800, fontSize: '1rem', color: '#0D5E6B' },
  progressBar:  { height: 6, background: '#E5E7EB', borderRadius: 99, overflow: 'hidden', marginBottom: 6 },
  progressFill: { height: '100%', background: 'linear-gradient(90deg, #0D5E6B, #1A8FA0)', borderRadius: 99, transition: 'width 0.4s ease' },
  stepLabel:    { fontSize: '0.72rem', color: '#9CA3AF', fontWeight: 600 },
  form:         { display: 'flex', flexDirection: 'column', gap: 16 },
  title:        { fontFamily: 'Inter, sans-serif', fontSize: '1.5rem', fontWeight: 800, color: '#0D5E6B', margin: 0 },
  sub:          { fontSize: '0.875rem', color: '#6B7280', margin: 0 },
  row:          { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 },
  field:        { display: 'flex', flexDirection: 'column', gap: 5 },
  label:        { fontSize: '0.78rem', fontWeight: 600, color: '#374151', textTransform: 'uppercase', letterSpacing: '0.05em' },
  input:        { padding: '10px 13px', borderRadius: 10, border: '1.5px solid #D1D5DB', fontSize: '0.88rem', color: '#1F2937', background: '#fff', outline: 'none' },
  errorMsg:     { fontSize: '0.82rem', color: '#EF4444', background: '#FEF2F2', border: '1px solid #FECACA', borderRadius: 8, padding: '8px 12px', margin: 0 },
  primaryBtn:   { padding: '13px', background: 'linear-gradient(135deg, #0D5E6B, #1A8FA0)', color: '#fff', border: 'none', borderRadius: 10, fontFamily: 'Inter, sans-serif', fontWeight: 700, fontSize: '0.95rem', cursor: 'pointer' },
  secondaryBtn: { padding: '11px', background: '#F3F4F6', color: '#374151', border: 'none', borderRadius: 10, fontFamily: 'Inter, sans-serif', fontWeight: 600, fontSize: '0.88rem', cursor: 'pointer' },
  backLink:     { textAlign: 'center', fontSize: '0.82rem', color: '#6B7280', margin: 0 },
  link:         { color: '#0D5E6B', fontWeight: 600, textDecoration: 'none' },
  consentList:  { display: 'flex', flexDirection: 'column', gap: 12, maxHeight: 280, overflowY: 'auto', padding: '4px 0', scrollbarWidth: 'thin' },
  consentItem:  { padding: '12px 14px', background: '#F8FAFB', borderRadius: 10, border: '1px solid #E5E7EB' },
  consentTitle: { fontSize: '0.8rem', fontWeight: 700, color: '#0D5E6B', marginBottom: 4 },
  consentText:  { fontSize: '0.78rem', color: '#4B5563', lineHeight: 1.6 },
  checkboxRow:  { display: 'flex', alignItems: 'flex-start', gap: 10, cursor: 'pointer', padding: '12px 14px', background: '#EFF6FF', borderRadius: 10, border: '1.5px solid #BFDBFE' },
  checkboxLabel:{ fontSize: '0.85rem', fontWeight: 600, color: '#1D4ED8', lineHeight: 1.4 },
  eyeBtn:       { position: 'absolute', right: 12, background: 'none', border: 'none', cursor: 'pointer', color: '#9CA3AF', display: 'flex', alignItems: 'center' },
  inlineError: {
    color: '#EF4444',
    fontSize: '0.75rem',
    marginTop: -4,
    marginBottom: 4,
    textAlign: 'left'
  }
};
