-- Create custom types
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE user_role AS ENUM ('parent', 'practitioner', 'learner');
CREATE TYPE doc_type AS ENUM ('OT_Evaluation', 'IEP', 'ISP', 'Speech_Language', 'Biomedical', 'Home_Plan', 'Protocol', 'School_Report', 'Other');
CREATE TYPE doc_status AS ENUM ('processing', 'definitive', 'derived', 'error');
CREATE TYPE difficulty_mode AS ENUM ('Easy', 'Medium', 'Complex - Words', 'Complex - Sentences', 'Self Expression');
CREATE TYPE keyboard_size AS ENUM ('Big keys', 'Medium keys', 'Standard keys');

-- Users table (extends Supabase auth.users)
CREATE TABLE public.users (
    id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
    role user_role NOT NULL,
    first_name TEXT,
    last_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Children table
CREATE TABLE public.children (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    parent_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    first_name TEXT NOT NULL,
    last_name TEXT,
    age INTEGER,
    diagnosis TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Practitioner-Child relationships
CREATE TABLE public.practitioner_children (
    practitioner_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    child_id UUID REFERENCES public.children(id) ON DELETE CASCADE,
    granted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (practitioner_id, child_id)
);

-- Documents table
CREATE TABLE public.documents (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    child_id UUID REFERENCES public.children(id) ON DELETE CASCADE,
    file_name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    file_type doc_type NOT NULL,
    status doc_status DEFAULT 'processing',
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Atlas Profiles table (The 360 profile generated by AI)
CREATE TABLE public.atlas_profiles (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    child_id UUID REFERENCES public.children(id) ON DELETE CASCADE UNIQUE,
    completeness_percentage INTEGER DEFAULT 0,
    strengths JSONB DEFAULT '[]'::jsonb,
    challenges JSONB DEFAULT '[]'::jsonb,
    communication_profile JSONB DEFAULT '{}'::jsonb,
    sensory_profile JSONB DEFAULT '{}'::jsonb,
    functional_wellness JSONB DEFAULT '[]'::jsonb,
    motor_reflexes JSONB DEFAULT '[]'::jsonb,
    cross_report_insights JSONB DEFAULT '[]'::jsonb,
    home_plan JSONB DEFAULT '{}'::jsonb,
    calibration_parameters JSONB DEFAULT '{}'::jsonb, -- LetterQuest settings
    care_navigator JSONB DEFAULT '{}'::jsonb,
    last_updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- LetterQuest Sessions table
CREATE TABLE public.sessions (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    child_id UUID REFERENCES public.children(id) ON DELETE CASCADE,
    session_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    difficulty_mode difficulty_mode NOT NULL,
    keyboard_size keyboard_size NOT NULL,
    accuracy INTEGER,
    words_completed INTEGER,
    sentences_completed INTEGER,
    average_response_time_ms INTEGER,
    overrides_made JSONB DEFAULT '[]'::jsonb
);

-- Consent table
CREATE TABLE public.consent (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    parent_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    agreement_version TEXT NOT NULL,
    accepted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    ip_address TEXT,
    shared_sections JSONB DEFAULT '[]'::jsonb
);

-- Enable RLS
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.children ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.practitioner_children ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.atlas_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consent ENABLE ROW LEVEL SECURITY;

-- Note: For the prototype, we will use the service_role key for backend operations or disable RLS for local testing if needed.
-- Proper RLS policies should be implemented for production.
